name: .NET Build Verification
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7
        with:
          dotnet-version: "10.0.x"

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: trust dev certs
        run: SSL_CERT_DIR="$HOME/.aspnet/dev-certs/trust" dotnet dev-certs https --trust
      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal
